/**
 * Generates supabase/seed.sql from the current seed data modules.
 * Run: node scripts/gen-seed.ts > supabase/seed.sql
 *
 * The data files only use `import type`, so Node's type stripping can import
 * them without resolving the "@/" path alias at runtime.
 */
import { portfolioItems } from "../src/lib/data/portfolio.ts";
import { faqItems } from "../src/lib/data/faq.ts";
import { glossaryTerms } from "../src/lib/data/glossary.ts";
import { blogPosts } from "../src/lib/data/blog.ts";
import { guideSections } from "../src/lib/data/guide.ts";
import { siteContact } from "../src/lib/site.ts";

const q = (s: string | null | undefined) =>
  s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));
const arr = (items: string[]) =>
  items.length ? `array[${items.map(q).join(",")}]::text[]` : `'{}'::text[]`;

const out: string[] = [];
out.push("-- AUTO-GENERATED by scripts/gen-seed.ts — run ONCE on an empty DB.");
out.push("-- Supabase Dashboard → SQL Editor → paste → Run.\n");

out.push("-- Clear existing seed (safe on a fresh DB)");
out.push("truncate table guide_item, guide_section, faq, glossary restart identity cascade;\n");

// portfolio
out.push("-- portfolio");
portfolioItems.forEach((p, i) => {
  out.push(
    `insert into portfolio (item_no,name_en,name_kr,hover_en,hover_kr,use_field,material,package_type,package_form,printing,coating_en,coating_kr,finishing_en,finishing_kr,dim_l,dim_w,dim_h,sort) values (` +
      [
        q(p.itemNo), q(p.name.en), q(p.name.ko), q(p.hover.en), q(p.hover.ko),
        q(p.useField), q(p.material), q(p.packageType), q(p.packageForm),
        arr(p.printing), q(p.coating.en), q(p.coating.ko), q(p.finishing.en), q(p.finishing.ko),
        n(p.dims.l), n(p.dims.w), n(p.dims.h), n(i),
      ].join(",") +
      `) on conflict (item_no) do nothing;`,
  );
});
out.push("");

// faq
out.push("-- faq");
faqItems.forEach((f, i) => {
  out.push(
    `insert into faq (category,q_en,q_kr,a_en,a_kr,sort) values (` +
      [q(f.category), q(f.q.en), q(f.q.ko), q(f.a.en), q(f.a.ko), n(i)].join(",") +
      `);`,
  );
});
out.push("");

// glossary
out.push("-- glossary");
glossaryTerms.forEach((g, i) => {
  out.push(
    `insert into glossary (category,term_en,term_kr,desc_en,desc_kr,tags_en,tags_kr,related_portfolio_ids,sort) values (` +
      [
        q(g.category), q(g.term.en), q(g.term.ko), q(g.desc.en), q(g.desc.ko),
        arr(g.tags.map((t) => t.en)), arr(g.tags.map((t) => t.ko)),
        arr(g.relatedPortfolioIds), n(i),
      ].join(",") +
      `);`,
  );
});
out.push("");

// blog
out.push("-- blog");
blogPosts.forEach((b) => {
  out.push(
    `insert into blog (slug,category,title_en,title_kr,summary_en,summary_kr,published_at) values (` +
      [
        q(b.slug), q(b.category), q(b.title.en), q(b.title.ko),
        q(b.summary.en), q(b.summary.ko), q(b.date),
      ].join(",") +
      `) on conflict (slug) do nothing;`,
  );
});
out.push("");

// guide
out.push("-- guide");
guideSections.forEach((s, si) => {
  out.push(
    `insert into guide_section (key,title_en,title_kr,sort) values (${q(s.id)},${q(s.title.en)},${q(s.title.ko)},${n(si)});`,
  );
  s.items.forEach((it, ii) => {
    out.push(
      `insert into guide_item (section_id,title_en,title_kr,subtitle,desc_en,desc_kr,tip_en,tip_kr,sort) values (` +
        [
          `(select id from guide_section where key=${q(s.id)} limit 1)`,
          q(it.title.en), q(it.title.ko), q(it.subtitle ?? ""),
          q(it.desc.en), q(it.desc.ko),
          q(it.tip?.en ?? ""), q(it.tip?.ko ?? ""), n(ii),
        ].join(",") +
        `);`,
    );
  });
});
out.push("");

// site_settings
out.push("-- site settings");
out.push(
  `update site_settings set company_en=${q(siteContact.companyEn)}, company_kr=${q(siteContact.companyKo)}, ceo_en=${q(siteContact.ceoEn)}, ceo_kr=${q(siteContact.ceoKo)}, email=${q(siteContact.email)}, phone=${q(siteContact.phone)}, whatsapp=${q(siteContact.whatsapp)}, biz_no=${q(siteContact.bizNo)}, address_en=${q(siteContact.addressEn)}, address_kr=${q(siteContact.addressKo)}, instagram=${q(siteContact.instagram)}, blog_url=${q(siteContact.blog)} where id=1;`,
);

console.log(out.join("\n"));
